#!/usr/bin/env bash
# =========================================================================
# Script de déploiement automatique — Trello clone sur Hetzner.
#
# Idempotent : peut être relancé à tout moment. Construit le container
# frontend, met à jour le Caddyfile CHADIA (avec sauvegarde) et recharge
# Caddy sans downtime.
#
# Usage (sur le serveur Hetzner) :
#   cd /home/hermes/trello-clone
#   bash deploy/deploy.sh
# =========================================================================

set -euo pipefail

# Sur ce serveur Hetzner, le DOCKER_HOST par défaut pointe sur un socket
# rootless inexistant. On force toujours le socket système.
export DOCKER_HOST="unix:///var/run/docker.sock"

# --- Configuration ----------------------------------------------------------
TRELLO_DOMAIN="projetsynergie.fr"
CHADIA_CADDYFILE="/home/hermes/chadia-projects/Caddyfile"
PROJECT_DIR="/home/hermes/trello-clone"
CADDY_CONTAINER="chadia-projects-caddy-1"
ENV_FILE="$PROJECT_DIR/.env.production"

cd "$PROJECT_DIR"

# --- Étape 1 : Générer .env.production s'il n'existe pas --------------------
if [ ! -f "$ENV_FILE" ]; then
  echo "→ Création de $ENV_FILE..."
  SECRET=$(openssl rand -base64 32 | tr -d '\n')
  cat > "$ENV_FILE" <<EOF
# Variables prod Trello clone — NE PAS COMMITTER (ignoré par .gitignore)
TRELLO_DOMAIN=$TRELLO_DOMAIN
BETTER_AUTH_SECRET=$SECRET
EOF
  chmod 600 "$ENV_FILE"
  echo "  ✓ Secret BETTER_AUTH généré."
else
  echo "→ $ENV_FILE existe déjà, conservation."
fi

# --- Étape 2 : Vérifier la propagation DNS ---------------------------------
echo "→ Vérification DNS..."
EXPECTED_IP="188.245.42.63"
ALL_OK=true
for SUB in trello api auth; do
  RESOLVED=$(dig "$SUB.$TRELLO_DOMAIN" +short 2>/dev/null | head -1)
  if [ "$RESOLVED" = "$EXPECTED_IP" ]; then
    echo "  ✓ $SUB.$TRELLO_DOMAIN → $EXPECTED_IP"
  else
    echo "  ✗ $SUB.$TRELLO_DOMAIN → '$RESOLVED' (attendu $EXPECTED_IP)"
    ALL_OK=false
  fi
done
if [ "$ALL_OK" = false ]; then
  echo ""
  echo "⚠  DNS pas encore propagé. Attends 5-30 min et relance ce script."
  echo "   Continue quand même ? (y/N)"
  read -r CONTINUE
  if [ "$CONTINUE" != "y" ]; then
    exit 1
  fi
fi

# --- Étape 3a : S'assurer que Caddy CHADIA a accès au réseau de Convex -----
echo "→ Connexion de Caddy au réseau Convex (idempotent)..."
docker network connect trello-clone-dev_default "$CADDY_CONTAINER" 2>/dev/null || true
echo "  ✓ Caddy peut joindre trello-convex-backend"

# --- Étape 3b : Build & run le container frontend --------------------------
echo "→ Build container trello-frontend..."
docker compose --env-file "$ENV_FILE" -f docker-compose.production.yml up -d --build

echo "  Attente du healthcheck (30s)..."
sleep 30
if docker ps --filter "name=trello-frontend" --filter "health=healthy" --format "{{.Names}}" | grep -q trello-frontend; then
  echo "  ✓ trello-frontend healthy"
else
  echo "  ⚠ healthcheck pas encore OK. Logs :"
  docker logs --tail 30 trello-frontend
fi

# --- Étape 4 : Générer le bloc Caddy avec le bon domaine -------------------
CADDY_FRAGMENT=$(sed "s/{DOMAIN}/$TRELLO_DOMAIN/g" "$PROJECT_DIR/deploy/Caddyfile.trello")

# Marqueurs uniques pour idempotence (re-exécution du script ne duplique pas)
START_MARKER="# === BEGIN trello-clone (auto-generated by deploy.sh) ==="
END_MARKER="# === END trello-clone ==="

# Backup du Caddyfile avant modification
BACKUP="$CHADIA_CADDYFILE.bak.$(date +%Y%m%d-%H%M%S)"
cp "$CHADIA_CADDYFILE" "$BACKUP"
echo "→ Caddyfile CHADIA backupé : $BACKUP"

# Si le bloc Trello existe déjà, on le remplace ; sinon on l'ajoute à la fin.
if grep -q "$START_MARKER" "$CHADIA_CADDYFILE"; then
  echo "→ Bloc trello-clone déjà présent, mise à jour..."
  # Supprime de START_MARKER à END_MARKER inclus
  sed -i "/$START_MARKER/,/$END_MARKER/d" "$CHADIA_CADDYFILE"
fi

# Ajoute le nouveau bloc à la fin
cat >> "$CHADIA_CADDYFILE" <<EOF

$START_MARKER
$CADDY_FRAGMENT
$END_MARKER
EOF

echo "  ✓ Caddyfile CHADIA mis à jour."

# --- Étape 5 : Validation + reload Caddy ----------------------------------
echo "→ Validation syntaxe Caddyfile..."
if docker exec "$CADDY_CONTAINER" caddy validate --config /etc/caddy/Caddyfile 2>&1 | tail -3; then
  echo "  ✓ Syntaxe OK"
else
  echo "  ✗ Caddyfile invalide ! Restauration du backup..."
  cp "$BACKUP" "$CHADIA_CADDYFILE"
  exit 1
fi

echo "→ Reload Caddy (sans downtime)..."
docker exec "$CADDY_CONTAINER" caddy reload --config /etc/caddy/Caddyfile
echo "  ✓ Caddy rechargé"

# --- Étape 6 : Test HTTPS final --------------------------------------------
echo ""
echo "→ Test des endpoints..."
sleep 5
for SUB in trello api auth; do
  CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://$SUB.$TRELLO_DOMAIN" --max-time 10 || echo "ERR")
  echo "  https://$SUB.$TRELLO_DOMAIN → HTTP $CODE"
done

echo ""
echo "========================================="
echo "✓ Déploiement terminé"
echo "========================================="
echo ""
echo "App live : https://trello.$TRELLO_DOMAIN"
echo ""
echo "Logs    : docker logs -f trello-frontend"
echo "Caddy   : docker logs -f $CADDY_CONTAINER"
echo "Rollback: cp $BACKUP $CHADIA_CADDYFILE && docker exec $CADDY_CONTAINER caddy reload --config /etc/caddy/Caddyfile"
